#!/bin/sh
############
# On Ubuntu, copy this file to /etc/network/if-up.d and modify it.
# Romeve rule first, then add a new rule to avoid duplicate rules.
# On ubuntu 18, install ifupdown to support it
#      apt install ifupdown resolvconf
############
#ADD_LOCAL_NAT=/home/username/projects/ServerTools/ubuntu/iptables-tools/addLocalNAT.sh
#REMOVE_LOCAL_NAT=/home/username/projects/ServerTools/ubuntu/iptables-tools/removeLocalNAT.sh

# http to 10.10.1.11
#${REMOVE_LOCAL_NAT} enp2s0 80 10.10.1.11 80
#${ADD_LOCAL_NAT} enp2s0 80 10.10.1.11 80

# https to 10.10.1.11
#${REMOVE_LOCAL_NAT} enp2s0 80 10.10.1.11 443
#${ADD_LOCAL_NAT} enp2s0 80 10.10.1.11 443

# range ports to 10.10.1.11
#${REMOVE_LOCAL_NAT} enp2s0 3011:3020 10.10.1.11 3011-3020 multi
#${ADD_LOCAL_NAT} enp2s0 3011:3020 10.10.1.11 3011-3020 multi 

exit 0
